apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  REACT_APP_API_URL: "http://localhost:5000/api"
  DB_HOST: "172.17.0.2"      <RDS DB HOST>
  DB_NAME: "Users"

  
  # Add more configuration items here as needed
---
apiVersion: v1
kind: Secret
metadata:
  name: db-secret
type: Opaque
data:
  db-password: c2VjcmV0cGFzcw==  # Base64-encoded 'secretpass' <encode it when using>
