name: CI Pipeline

on:
  push:
    paths:
      - 'services/frontend/**'
    
  pull_request:
    paths:
      - 'services/frontend/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.x' # Adjust to the version of Node.js you need

    - name: Install dependencies
      run: |
        npm install

    - name: Run code quality checks
      run: |
        npx eslint services/frontend/**
        npx stylelint 'services/frontend/**/*.{css,scss}'

    - name: Run code styling
      run: |
        npx prettier --check src/
        npx stylelint --fix 'services/frontend/**/*.{css,scss}'

    - name: Build React app
      run: |
        npm run build

    - name: Login to AWS
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Build Docker image
      run: |
        docker build -t frontend:latest .

    - name: Log in to Amazon ECR
      id: ecr
      run: |
        aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | docker login --username AWS --password-stdin ${{ secrets.ECR_REGISTRY }}

    - name: Tag Docker image
      run: |
        docker tag my-image:latest ${{ secrets.ECR_REGISTRY }}/frontend:latest

    - name: Push Docker image to Amazon ECR
      run: |
        docker push ${{ secrets.ECR_REGISTRY }}/frontend:latest
